export default{
    authenticated: false,
    userEmail: 'fake@email.com',
    searchTerm: '',
    ime:'',
  prezime:'',
  adresa:'',
  grad:'',
  zip:'',
  number:'',
  datum:'',
  vrijeme:'',
  tekst:'',
  year:'',
  brtel:'',
  brtel2:'',
  odabirgrada:'',
  auto:'',
  tipKorisnika: '',
  podaci:'',
  cards: null,
  podaci:'',
      podaci1:'',
      podaci2:[],
      napomena:'',
      textComment:'',
      activeUserDetailsId:null,
      stanje:'',
      stanjepodaci:[],
      myEmail:'Loading...',
      myUserType:'',
      korisnickipodaci:[],
      napomena:null,
      aktivnikorisnik:null,
      status:'',
      radiona:'',
      imageData: null,
      email:'',
      polje:[],
      naslov:'',
      recenzije:[],
      opis:'',
      id:'',
      url:'',
      star:'',
      text:'',
      prihvacennovitermin: '',
      komentar:null,
      activeuser:null,
      uploadValue: 0,
      recenzija:''
}